# Generated by Django 3.0.3 on 2020-04-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200413_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Сборка', 'verbose_name_plural': 'Сборки'},
        ),
        migrations.RemoveField(
            model_name='computer',
            name='power_supply',
        ),
        migrations.AddField(
            model_name='computer',
            name='cooler',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Cooler'),
        ),
    ]
