# Generated by Django 3.0.3 on 2020-04-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200413_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooler',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='coolers/'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='corpuses/'),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='graphics/'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='powers/'),
        ),
        migrations.AddField(
            model_name='processor',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='processors'),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='rams/'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='computers/'),
        ),
    ]
