# Generated by Django 3.0.3 on 2020-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200413_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('memory', models.IntegerField(blank=True, default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='processors')),
                ('manufacturer', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('socket', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='motherboards/')),
                ('chipset', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manufacturer', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
            },
        ),
        migrations.AddField(
            model_name='cooler',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='memory',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='memory',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
