# Generated by Django 3.0.3 on 2020-04-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200413_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='hard',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.HardDisk'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='motherboard',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.MotherBoard'),
        ),
    ]
