# Generated by Django 3.0.3 on 2020-04-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200413_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='nmb',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
