# Generated by Django 3.0.3 on 2020-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_ram_nmb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harddisk',
            options={'verbose_name': 'Жесткий диск', 'verbose_name_plural': 'Жесткие диски'},
        ),
        migrations.RemoveField(
            model_name='computer',
            name='image',
        ),
        migrations.AlterField(
            model_name='harddisk',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hards/'),
        ),
    ]
